"use client";

import { useState } from "react";
import { Activity, AlertTriangle, ArrowRightLeft, Boxes, ChevronRight, Clock3, FileJson, LayoutDashboard, LockKeyhole, LogOut, Menu, MoonStar, RotateCcw, ShieldAlert, Sunrise, Users, X } from "lucide-react";
import { logout } from "@/app/actions/auth";
import { bypassReviewGate, createDeliveryCycle, lockCycleScope, overrideAiTaskPlan, reassignTask, updateClientCapacity, updateCycleStatus } from "@/app/admin/actions";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";

type CycleStatus = "intake_open" | "scope_locked" | "in_sprint" | "dawn_delivery";
type Props = {
  userName: string;
  companies: { id: string; name: string; capacityLimit: number }[];
  projects: { id: string; name: string; company: { name: string } }[];
  cycles: { id: string; date: string; status: CycleStatus; isActive: boolean; scopeLockedAt: string | null; project: { name: string; company: { name: string; capacityLimit: number } } | null; _count: { tasks: number } }[];
  tasks: { id: string; key: string; title: string; status: string; aiParsedChecklist: unknown; updatedAt: string; project: { name: string; companyId: string }; assignee: { id: string; name: string | null; email: string | null } | null }[];
  developers: { id: string; name: string | null; email: string | null; companyMemberships: { companyId: string }[] }[];
  audit: { id: string; action: string; createdAt: string; actor: { name: string | null; email: string | null }; task: { key: string; title: string } | null }[];
};

const cycleSteps: { id: CycleStatus; label: string }[] = [{ id: "intake_open", label: "Intake open" }, { id: "scope_locked", label: "Scope locked" }, { id: "in_sprint", label: "In sprint" }, { id: "dawn_delivery", label: "Dawn delivery" }];

export function AdminCommandCenter(props: Props) {
  const [section, setSection] = useState<"overview" | "cycles" | "dispatch" | "review" | "audit">("overview");
  const [mobileOpen, setMobileOpen] = useState(false);
  const reviewTasks = props.tasks.filter((task) => task.status === "pending_senior_review");
  const nav = [{ id: "overview", label: "Command overview", icon: LayoutDashboard }, { id: "cycles", label: "Delivery cycles", icon: MoonStar }, { id: "dispatch", label: "Task & pod dispatch", icon: ArrowRightLeft }, { id: "review", label: "Review fallback", icon: ShieldAlert }, { id: "audit", label: "Audit log", icon: Activity }] as const;
  return <main className="min-h-dvh bg-[#f4f7f4] text-slate-900">
    {mobileOpen && <button aria-label="Close navigation" className="fixed inset-0 z-30 bg-slate-950/30 lg:hidden" onClick={() => setMobileOpen(false)} />}
    <aside className={`fixed inset-y-0 left-0 z-40 flex w-72 flex-col border-r border-slate-200 bg-[#102f24] text-white transition-transform lg:translate-x-0 ${mobileOpen ? "translate-x-0" : "-translate-x-full"}`}>
      <div className="flex h-20 shrink-0 items-center gap-3 border-b border-white/10 px-6"><span className="grid h-10 w-10 place-items-center rounded-xl bg-emerald-300 text-[#123426]"><Sunrise className="h-5 w-5" /></span><div><p className="font-semibold">Lumetha</p><p className="text-[10px] uppercase tracking-[.18em] text-emerald-100/55">Admin command center</p></div><button className="ml-auto lg:hidden" onClick={() => setMobileOpen(false)}><X className="h-5 w-5" /></button></div>
      <nav className="min-h-0 flex-1 overflow-y-auto px-3 py-6">{nav.map(({ id, label, icon: Icon }) => <button key={id} onClick={() => { setSection(id); setMobileOpen(false); }} className={`mb-1 flex w-full items-center gap-3 rounded-xl px-4 py-3 text-left text-sm transition ${section === id ? "bg-white/12 text-white" : "text-emerald-50/65 hover:bg-white/7 hover:text-white"}`}><Icon className="h-4 w-4" />{label}{id === "review" && reviewTasks.length > 0 && <span className="ml-auto rounded-full bg-amber-400 px-2 py-0.5 text-[10px] font-bold text-amber-950">{reviewTasks.length}</span>}</button>)}</nav>
      <div className="shrink-0 border-t border-white/10 p-4"><div className="mb-3 flex items-center gap-3 px-2"><span className="grid h-9 w-9 place-items-center rounded-full bg-white/10 text-xs font-semibold">{props.userName.slice(0,2).toUpperCase()}</span><div className="min-w-0"><p className="truncate text-sm font-medium">{props.userName}</p><p className="text-[10px] text-emerald-50/55">System administrator</p></div></div><form action={logout}><button className="flex w-full items-center gap-2 rounded-xl px-3 py-2 text-sm text-emerald-50/70 hover:bg-white/10 hover:text-white"><LogOut className="h-4 w-4" />Sign out</button></form></div>
    </aside>
    <div className="min-h-dvh lg:pl-72"><header className="sticky top-0 z-20 flex h-20 items-center border-b border-slate-200 bg-white/90 px-5 backdrop-blur sm:px-8"><button onClick={() => setMobileOpen(true)} className="mr-3 rounded-lg border p-2 lg:hidden"><Menu className="h-5 w-5" /></button><div><p className="text-xs font-semibold uppercase tracking-[.15em] text-emerald-700">Operations</p><h1 className="mt-1 text-lg font-semibold">{nav.find((item) => item.id === section)?.label}</h1></div><div className="ml-auto flex items-center gap-2 rounded-full bg-emerald-50 px-3 py-2 text-xs font-medium text-emerald-800"><span className="h-2 w-2 rounded-full bg-emerald-500" />Live · all systems</div></header>
      <div className="mx-auto max-w-[1500px] p-5 sm:p-8">
        {section === "overview" && <Overview {...props} reviewCount={reviewTasks.length} onNavigate={setSection} />}
        {section === "cycles" && <CycleManager cycles={props.cycles} projects={props.projects} />}
        {section === "dispatch" && <Dispatch tasks={props.tasks} developers={props.developers} companies={props.companies} />}
        {section === "review" && <ReviewFallback tasks={reviewTasks} />}
        {section === "audit" && <AuditFeed events={props.audit} />}
      </div>
    </div>
  </main>;
}

function Overview({ cycles, tasks, companies, developers, reviewCount, onNavigate }: Props & { reviewCount: number; onNavigate: (value: "cycles" | "dispatch" | "review") => void }) {
  const active = cycles.find((cycle) => cycle.isActive);
  const stats = [{ label: "Active cycle", value: active ? cycleSteps.find((s) => s.id === active.status)?.label ?? active.status : "Not started", detail: active?.project?.name ?? "Create tonight’s cycle", icon: MoonStar }, { label: "Tasks in flight", value: String(tasks.filter((t) => t.status === "in_progress").length), detail: `${tasks.length} total open`, icon: Boxes }, { label: "Review blockers", value: String(reviewCount), detail: "Awaiting senior validation", icon: ShieldAlert }, { label: "Developer pod", value: String(developers.length), detail: `${companies.length} client workspaces`, icon: Users }];
  return <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map(({ label, value, detail, icon: Icon }) => <Card key={label} className="rounded-2xl border-slate-200 shadow-none"><CardContent className="p-5"><div className="flex items-start justify-between"><div><p className="text-xs font-medium text-slate-500">{label}</p><p className="mt-3 text-2xl font-semibold tracking-tight">{value}</p><p className="mt-1 text-xs text-slate-500">{detail}</p></div><span className="grid h-10 w-10 place-items-center rounded-xl bg-emerald-50 text-emerald-700"><Icon className="h-5 w-5" /></span></div></CardContent></Card>)}</div><Card className="mt-6 rounded-2xl shadow-none"><CardHeader><CardTitle className="text-base">Tonight’s control path</CardTitle><CardDescription>Resolve the next operational action without leaving the command center.</CardDescription></CardHeader><CardContent className="grid gap-3 md:grid-cols-3"><QuickAction title="Manage cycle" detail="Lock scope or move the overnight sprint forward." onClick={() => onNavigate("cycles")} /><QuickAction title="Dispatch the pod" detail="Assign work and adjust AI task plans." onClick={() => onNavigate("dispatch")} /><QuickAction title="Clear review blockers" detail="Use audited fallback controls for stuck work." onClick={() => onNavigate("review")} /></CardContent></Card></>;
}
function QuickAction({ title, detail, onClick }: { title: string; detail: string; onClick: () => void }) { return <button onClick={onClick} className="flex items-center rounded-xl border border-slate-200 p-4 text-left hover:border-emerald-300 hover:bg-emerald-50/40"><div><p className="text-sm font-semibold">{title}</p><p className="mt-1 text-xs leading-5 text-slate-500">{detail}</p></div><ChevronRight className="ml-auto h-4 w-4 text-slate-400" /></button>; }

function CycleManager({ cycles, projects }: Pick<Props,"cycles"|"projects">) { return <div className="grid gap-6 xl:grid-cols-[1fr_340px]"><div className="space-y-4">{cycles.length ? cycles.map((cycle) => <Card key={cycle.id} className="rounded-2xl shadow-none"><CardHeader className="pb-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><CardTitle className="text-base">{cycle.project?.company.name ?? "Unassigned"} · {cycle.project?.name ?? "Cycle"}</CardTitle><CardDescription>{new Date(cycle.date).toLocaleDateString()} · {cycle._count.tasks}/{cycle.project?.company.capacityLimit ?? 0} capacity</CardDescription></div>{cycle.isActive && <span className="rounded-full bg-emerald-50 px-3 py-1 text-[10px] font-bold uppercase text-emerald-700">Active</span>}</div></CardHeader><CardContent><div className="grid gap-2 md:grid-cols-4">{cycleSteps.map((step, index) => <form key={step.id} action={updateCycleStatus}><input type="hidden" name="cycleId" value={cycle.id} /><input type="hidden" name="status" value={step.id} /><button className={`w-full rounded-xl border p-3 text-left ${cycle.status === step.id ? "border-emerald-600 bg-emerald-50" : "border-slate-200 hover:bg-slate-50"}`}><span className="block text-[10px] font-semibold text-slate-400">0{index + 1}</span><span className="mt-1 block text-xs font-semibold">{step.label}</span></button></form>)}</div>{cycle.status === "intake_open" && <form action={lockCycleScope} className="mt-4 flex justify-end"><input type="hidden" name="cycleId" value={cycle.id} /><Button className="rounded-xl bg-amber-500 text-amber-950 hover:bg-amber-400"><LockKeyhole />Lock scope</Button></form>}</CardContent></Card>) : <Card className="rounded-2xl p-10 text-center shadow-none"><MoonStar className="mx-auto h-7 w-7 text-slate-400" /><p className="mt-3 text-sm font-medium">No delivery cycles yet</p></Card>}</div><Card className="h-fit rounded-2xl shadow-none"><CardHeader><CardTitle className="text-base">Open a delivery cycle</CardTitle><CardDescription>Start intake for a project and date.</CardDescription></CardHeader><CardContent><form action={createDeliveryCycle} className="space-y-3"><select name="projectId" required className="h-10 w-full rounded-md border border-slate-200 bg-white px-3 text-sm">{projects.map((project) => <option key={project.id} value={project.id}>{project.company.name} · {project.name}</option>)}</select><Input type="date" name="date" required defaultValue={new Date().toISOString().slice(0,10)} /><Button className="w-full bg-[#173f2e] hover:bg-[#102f24]">Open intake</Button></form></CardContent></Card></div>; }

function Dispatch({ tasks, developers, companies }: Pick<Props,"tasks"|"developers"|"companies">) { const [editing, setEditing] = useState<string | null>(null); return <div className="space-y-6"><Card className="rounded-2xl shadow-none"><CardHeader><CardTitle className="text-base">Client capacity</CardTitle><CardDescription>Limit how much work can enter one overnight cycle.</CardDescription></CardHeader><CardContent className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{companies.map((company) => <form action={updateClientCapacity} key={company.id} className="flex items-center gap-3 rounded-xl border border-slate-200 p-3"><input type="hidden" name="companyId" value={company.id} /><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{company.name}</p><p className="text-[10px] text-slate-500">Tasks per cycle</p></div><Input name="capacityLimit" type="number" min="1" max="100" defaultValue={company.capacityLimit} className="w-20" /><Button size="sm" variant="outline">Save</Button></form>)}</CardContent></Card><div className="space-y-3">{tasks.map((task) => { const eligible = developers.filter((developer) => developer.companyMemberships.some((m) => m.companyId === task.project.companyId)); return <Card key={task.id} className="rounded-2xl shadow-none"><CardContent className="p-5"><div className="flex flex-wrap items-center gap-4"><div className="min-w-0 flex-1"><p className="font-mono text-[10px] text-slate-400">{task.key} · {task.project.name}</p><h3 className="mt-1 text-sm font-semibold">{task.title}</h3><p className="mt-1 text-xs text-slate-500">{task.status.replaceAll("_"," ")} · Updated {new Date(task.updatedAt).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</p></div><form action={reassignTask} className="flex gap-2"><input type="hidden" name="taskId" value={task.id} /><select name="developerId" required defaultValue={task.assignee?.id ?? ""} className="h-9 rounded-md border border-slate-200 bg-white px-2 text-xs"><option value="" disabled>Assign developer</option>{eligible.map((developer) => <option key={developer.id} value={developer.id}>{developer.name ?? developer.email}</option>)}</select><Button size="sm" variant="outline"><ArrowRightLeft />Assign</Button></form><Button size="sm" variant="outline" onClick={() => setEditing(editing === task.id ? null : task.id)}><FileJson />Edit AI plan</Button></div>{editing === task.id && <form action={overrideAiTaskPlan} className="mt-4 border-t border-slate-100 pt-4"><input type="hidden" name="taskId" value={task.id} /><textarea name="taskJson" required defaultValue={JSON.stringify(task.aiParsedChecklist ?? [], null, 2)} className="min-h-52 w-full rounded-xl border border-slate-200 bg-slate-950 p-4 font-mono text-xs leading-5 text-emerald-200" /><div className="mt-3 flex justify-end"><Button size="sm" className="bg-[#173f2e] hover:bg-[#102f24]">Validate & save override</Button></div></form>}</CardContent></Card>})}</div></div>; }

function ReviewFallback({ tasks }: { tasks: Props["tasks"] }) { return <div><div className="mb-5 rounded-2xl border border-amber-200 bg-amber-50 p-5"><div className="flex gap-3"><AlertTriangle className="h-5 w-5 shrink-0 text-amber-700" /><div><p className="text-sm font-semibold text-amber-950">Emergency control</p><p className="mt-1 text-xs leading-5 text-amber-800">Bypassing senior review is permanently audited. Use only when the normal review path is blocked and a verified deployment is ready.</p></div></div></div><div className="space-y-3">{tasks.length ? tasks.map((task) => <Card key={task.id} className="rounded-2xl shadow-none"><CardContent className="p-5"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-amber-50 text-amber-700"><Clock3 className="h-5 w-5" /></span><div><p className="text-sm font-semibold">{task.title}</p><p className="font-mono text-[10px] text-slate-500">{task.key} · {task.project.name}</p></div></div><form action={bypassReviewGate} className="mt-4 grid gap-3 md:grid-cols-[1fr_1fr_auto]"><input type="hidden" name="taskId" value={task.id} /><Input name="deploymentUrl" type="url" required placeholder="https://verified-staging.example" /><Input name="reason" required minLength={15} placeholder="Why the normal review gate is unavailable" /><Button className="bg-rose-700 hover:bg-rose-600"><RotateCcw />Bypass & ship</Button></form></CardContent></Card>) : <Card className="rounded-2xl p-12 text-center shadow-none"><ShieldAlert className="mx-auto h-7 w-7 text-emerald-600" /><p className="mt-3 text-sm font-medium">No blocked reviews</p><p className="mt-1 text-xs text-slate-500">The senior review queue is clear.</p></Card>}</div></div>; }

function AuditFeed({ events }: { events: Props["audit"] }) { return <Card className="rounded-2xl shadow-none"><CardHeader><CardTitle className="text-base">Immutable operations trail</CardTitle><CardDescription>Cycle, dispatch, override, and review-gate events.</CardDescription></CardHeader><CardContent><div className="relative space-y-0 before:absolute before:bottom-4 before:left-[15px] before:top-4 before:w-px before:bg-slate-200">{events.map((event) => <div key={event.id} className="relative flex gap-4 py-3"><span className="z-10 mt-1 h-8 w-8 shrink-0 rounded-full border-4 border-white bg-emerald-500" /><div><p className="text-sm font-medium">{event.action.replaceAll("_"," ")}</p><p className="mt-1 text-xs text-slate-500">{event.task ? `${event.task.key} · ${event.task.title} · ` : ""}{event.actor.name ?? event.actor.email} · {new Date(event.createdAt).toLocaleString()}</p></div></div>)}</div></CardContent></Card>; }
